version: "3.9"
services:
  web:
    # depends_on:
    #   - postgres
    build:
      context: ./Tourism
      dockerfile: Dockerfile
    image: tourism:v1
    environment:
      - PORT=8020
    env_file:
      - Tourism/.env
    ports:
      - "8000:8020"
    command: sh -c "chmod +x /app/collectstatic.sh && sh /app/collectstatic.sh && chmod +x /app/migrate.sh && sh /app/migrate.sh && /app/entrypoint.sh"
    volumes:
      - staticfiles:/app/staticfiles/
    networks:
      - backend
#   postgres:
#     image: postgres
#     # restart: always
#     env_file:
#       - Tourism/.env
#     expose:
#       - 5432
#     ports:
#       - 5432:5432
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     networks:
#       - backend

#   redis:
#     image: redis
#     # restart: always
#     expose:
#       - 6380
#     ports:
#       - "6380:6380"
#     volumes:
#       - redis_data:/data
#     entrypoint: redis-server --appendonly yes --port 6380
#     networks:
#       - backend

#   postgres-admin:
#     image: dpage/pgadmin4
#     ports:
#       - 8080:80
#     env_file:
#       - Tourism/.env
#     networks:
#       - backend

volumes:
  # postgres_data:
  # redis_data:
  staticfiles:
    # external: true

networks:
  backend: