# Generated by Django 4.0.6 on 2022-08-30 09:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_place', models.CharField(max_length=150, null=True)),
                ('type', models.IntegerField(choices=[(1, 'State'), (2, 'District'), (3, 'City'), (4, 'Chc')], null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 8, 30, 18, 17, 45, 984053))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
            ],
        ),
    ]
