# Generated by Django 3.2.14 on 2022-08-01 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'managed': True},
        ),
    ]
