# Generated by Django 4.0.6 on 2022-08-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_board_accessuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='accessUser',
            new_name='writer',
        ),
        migrations.RemoveField(
            model_name='board',
            name='b_date',
        ),
        migrations.RemoveField(
            model_name='board',
            name='b_title',
        ),
        migrations.RemoveField(
            model_name='board',
            name='b_writer',
        ),
        migrations.AddField(
            model_name='board',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
