# Generated by Django 4.0.6 on 2022-08-26 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_alter_board_created_at_alter_reviewimg_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewimg',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='board',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 17, 16, 35, 178692)),
        ),
        migrations.AlterField(
            model_name='reviewimg',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 17, 16, 35, 178692)),
        ),
    ]
