# Generated by Django 4.0.6 on 2022-08-26 08:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_rename_user_id_reviewimg_user_alter_board_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewimg',
            name='user',
        ),
        migrations.AddField(
            model_name='reviewimg',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.board'),
        ),
        migrations.AlterField(
            model_name='board',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 17, 28, 42, 531226)),
        ),
        migrations.AlterField(
            model_name='reviewimg',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 17, 28, 42, 531226)),
        ),
    ]
