# Generated by Django 4.0.6 on 2022-08-31 01:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_location_created_at'),
        ('board', '0013_alter_board_created_at_alter_reviewimg_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location'),
        ),
        migrations.AlterField(
            model_name='board',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 31, 10, 14, 9, 844428)),
        ),
        migrations.AlterField(
            model_name='reviewimg',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 31, 10, 14, 9, 844928)),
        ),
    ]
